repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.7.0
    hooks:
      - id: ruff
        args: [--fix]
        files: ^(backend|infra/cdk)/.*\.py$
      - id: ruff-format
        files: ^(backend|infra/cdk)/.*\.py$
